### PR TITLE
Update NPM Badge

### PR DESCRIPTION
**Pull request by nguyenchr**

### CODE REVIEW

**Comment by richjharris** [comment]
:+1:
Not related to this PR but the license badge is showing as `undefined`. I assume it needs to be set in npm to pick it up.

**Comment by nicholasf** [comment]
Yes, I was waiting for @rprieto to get back to fix that. Could look into it before then if you like.

**Comment by nicholasf** [comment]
Thanks @nguyenchr !

**Comment by nguyenchr** [comment]
looks like the license badge is pointing to `node-strummer-middleware` rather than `strummer-middleware` which it is on npm

**Comment by nicholasf** [comment]
I'll look at it now.

**Pull request merged**
