### PR TITLE
Add ability to set custom areas for validation

### PR DESCRIPTION
**Pull request by richjharris**
/cc @nguyenchr @nicholasf

### CODE REVIEW

**Comment by nicholasf** [comment]
Looks good though I think the new function, `setArea` needs its own `describe` clause in the `index-test.js`. So, something like `describe('#setArea') ...`. 

Could we add a test that shows a success condition? 

Also, I am wondering if we should rename areas to `VALIDATION_AREAS`, now that we have added a DSL that lets users extend them. Mainly because `sware.setValidationArea` communicates a bit more than `sware.setArea`. We could also add some doc above the `AREAS` declaration that explains they are areas of the request.

**Comment by richjharris** [comment]
@nicholasf updates made

**Comment by nicholasf** [comment]
👍  Merging this.

**Comment by nicholasf** [comment]
@richjharris we should probably make this a 1.0.1 release in package.json and npm. Will work on this tomorrow.

**Pull request merged**
